server:
  port: "8080"
  host: "localhost"

database:
  host: db
  port: "5432"
  name: "checkout_db"
  user: "postgres"
  password: "b2TcGMtoh1LogbL0EKyn0kUZufBHLbcP"
  sslmode: "disable"

app:
  environment: "development"
  debug: true