server:
  port: "8080"
  host: "0.0.0.0"

database:
  host: "localhost"
  port: "5432"
  name: "checkout_db"
  user: "postgres"
  password: "password"
  sslmode: "disable"

app:
  environment: "development"
  debug: true