networks:
  checkout-net:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    container_name: checkout-db
    environment:
      - POSTGRES_DB=checkout_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=b2TcGMtoh1LogbL0EKyn0kUZufBHLbcP
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - checkout-net

  app:
    container_name: checkout-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - checkout-net

volumes:
  postgres_data: